### ISSUE TITLE
munin plugin run: read_bme280 not found

### ISSUE THREAD

**Issue by banzo** [kbrownlees/bme280#1]
On Raspbian (Jessie), the read_bme binary is not known by the plugin:

```
$ sudo munin-run bme280_temperature
/etc/munin/plugins/bme280_humidity: 21: /etc/munin/plugins/bme280_humidity: read_bme280: not found
```

**Comment by banzo** [comment]
If I specify the full path in the plugin file then it is ok:

`CMD="/usr/local/bin/read_bme280 --pressure"`

instead of 

`CMD="read_bme280 --pressure`

Not sure how to fix that properly, maybe it is a bad idea to hardcode the full binary path in the config file since it could change depending on the distribution.

**Comment by kbrownlees** [comment]
Thanks for the report - I had it symlinked locally, whoops!

Should be able to add the following to the [bme280_*] section in /etc/munin/plugin-conf.d/munin-node:

```
env.PATH /usr/local/bin:/usr/bin
```
